// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPm3_MxU8HKkhUxBr-1u4FKdsN0JvqrOM',
    appId: '1:272235966928:android:e1d4a803cfce66d9a449d5',
    messagingSenderId: '272235966928',
    projectId: 'se7ety-77899',
    databaseURL: 'https://se7ety-77899-default-rtdb.firebaseio.com',
    storageBucket: 'se7ety-77899.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNFm6n0zQKkasDIXg-PTl8AudRYojfbQw',
    appId: '1:272235966928:ios:f050e82c959e1560a449d5',
    messagingSenderId: '272235966928',
    projectId: 'se7ety-77899',
    databaseURL: 'https://se7ety-77899-default-rtdb.firebaseio.com',
    storageBucket: 'se7ety-77899.firebasestorage.app',
    iosClientId: '272235966928-ocodssf11tp2vkmo2nmbrkv25njv9fqa.apps.googleusercontent.com',
    iosBundleId: 'com.se7ety.se7ety',
  );

}